### ISSUE TITLE
[SDK] Descriptor editing

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#273]
As part of the same page as "package description", scrolling a bit down you'll find the next step which is called "Descriptor edit". 
- Include title "Descriptor edit" next to a circle that will indicate its status
- Include one NSD _description_ text input (you'll find several all over the app so you can just adapt them easily without having to create it from scratch)
- Include as many VNFD _description_ text inputs as the number it was included in the input above "number of vnf"
- Include error messages (as in the second image) if one of the fields is not correct or if it was skipped.

Attached picture of the final result:
![sdkcreationpage_4](https://user-images.githubusercontent.com/35800470/55079432-720bb180-509c-11e9-980a-2439ff526072.png)

![sdkcreationpage_5](https://user-images.githubusercontent.com/35800470/55079855-4d640980-509d-11e9-9464-920b0833fe1c.png)

![sdkcreationpage_6](https://user-images.githubusercontent.com/35800470/55079817-3de4c080-509d-11e9-8dde-195e6e38a689.png)

**Comment by stefanbschneider** [comment]
Once the generation of descriptors works, I'd next do editing, but I'd try to use existing software for it

- eg, https://www.theia-ide.org/ (like VS code, but in browser), http://codiad.com/ (no longer maintained)
- When displaying the descriptors (https://github.com/sonata-nfv/tng-portal/issues/269), a "edit" button should simply open this web IDE (which should come installed with tng-project), which could then be used for editing the descriptors or even uploading additional files
- No need for Tango theming. If possible adjust colors, but let's keep this simple at this point
- Should do this even before implementing the next step (validation) because this would be something nice to show and actually be useful

**Comment by stefanbschneider** [comment]
Note to self: Using Theia IDE, I see two options for editing descriptors and existing projects:

* Use a shared Docker volume for both Theia and tng-sdk-project to read and write projects/descriptors. Would require small adjustments of tng-sdk-project to work with volumes and a Docker compose file to easily start and stop both containers. But I could use the Theia container as is.
* Combine tng-sdk-project and Theia in a single Docker container. Would require installing Theia inside the existing Dockerfile. But would probably work without volumes. (projects are lost after restart, but doesn't matter).

I'll try to go with the first option as it is more modular and seems easier.

**Comment by stefanbschneider** [comment]
Update/note for self:

`tng-sdk-project` supports Docker volumes now. When starting Theia IDE with the same volume, I can see the project files, but I can't edit them. See issue opened here: https://github.com/theia-ide/theia/issues/5842

This is the Docker compose file: https://github.com/stefanbschneider/tng-sdk-project/blob/dev/general/docker-compose.yml

**Comment by stefanbschneider** [comment]
Can't get either option to work: Build a single Docker image with the IDE inside or share a volume between the images...
See open issue at Theia

**Comment by stefanbschneider** [comment]
Closed by #386
