### ISSUE TITLE
[SM Network instantiation] Check license validity before instantiating

### ISSUE THREAD

**Issue by anapolg** [sonata-nfv/tng-portal#306]
Check if instantiation is allowed taking into account the type of license. When the user selects an SLA, ping the SLAM with the following API for the Portal to check if that license is allowed to proceed with instantiation.

`curl -H "Content-type:application/json" http://pre-int-sp-ath.5gtango.eu:32002/api/v3/slas/licenses/status/{sla_uuid}/{ns_uuid}`

- If true then follow with instantiation.
- If false and license type is "public" or "trial" do not allow instantiation and inform the user “Trial license exceeded or allowed instances over passed”.
- If false and license type is private do not allow to instantiate and inform the user he needs to buy a license. Redirect the user to license buying page. Once the license is bought come back to instantiation process and try again. Needs #307 
`curl -X POST -H "Content-type:application/x-www-form-urlencoded" -d "ns_uuid=<>&sla_uuid=<>" http://localhost:8080/tng-sla-mgmt/api/slas/v1/licenses/buy`

[REST API](https://github.com/sonata-nfv/tng-sla-mgmt/wiki/API-Specification-master#licensing)
Related to https://github.com/sonata-nfv/tng-gtk-sp/issues/199

**Comment by anapolg** [comment]
Pending #307

**Comment by anapolg** [comment]
What if the user does not select an SLA @ekapassa ? Because SLA is not a mandatory field during network service instantiation.

**Comment by ekapassa** [comment]
@anapolg As we are considering the license information into the SLAs... if the user does not select an SLA during instantiation, this means that the NS has not a license. I don't see a way we can link it with a license if we haven't create the corresponding SLA with the license info (the way it is implemented right now anyway).    
@jbonnet am I right ???

**Comment by anapolg** [comment]
@ekapassa @jbonnet  but what if the NS is private and it needs a license? then we force the user to select an SLA to fulfill this requirement even if the user does not want to have an SLA associated?

**Comment by ekapassa** [comment]
@anapolg I see your doubt here.. But when we started designing the licensing , it was considered to be included into the SLA (you can see here: https://git.cs.upb.de/5gtango/UserStories/issues/297 .    

BUT as Ana mentioned (and I think she is right), having the license into the SLA, leading us to have the selection of the SLA (if there is one for this NS) mandatory during the NS instantiation.     

The reason for this, is if  for example we have a NS that the provider wants to be private. So, the provider is going t create an SLA Template for this NS with a private license inside this sla.     
Then,  a customer wants to instantiate this specific NS (WHICH IS A PRIVATE ONE). A we have it now the customer can request an instantiation without selected the sla. But in our case this is wrong, because it will lead us to an instantiation of a private NS without actually having this license.    

As a result, my opinion here is this: a) we cannot change the licensing design. it will continue to be included into the SLAs. b) in order to be correct i agree with Ana that _**we should make the selection of the SLA mandatory during the instantiation request**_.    

@jbonnet @carlos-f-parada @mtouloup what is your opinion here? Do you agree with this??

**Comment by carlos-f-parada** [comment]
@ekapassa @anapolg According to the design (proposed by @jbonnet I guess), Licensing is part of SLA (king of subset), so Licensing is described within an SLAs. In that sense, following what is there, the not selection of SLAs means that there are no licensing (I assume it is possible no having any Licensing...). In case we want Licensing and not SLAs (delay,,bandwidth, etc.), we just need to define the licensing part and keep empty the SLA stuff (I assume an SLA can have just the Licensing part and not the rest). Does this approach solve the problem, or am I still missing pieces on this view?

**Comment by anapolg** [comment]
Talking from Portal side:

> I assume an SLA can have just the Licensing part and not the rest

Not right now. The SLA template creation requires some mandatory fields relative to SLA part and actually, the license part is optional (fulfilled in the server side if empty with the default data: public....)

> I assume it is possible no having any Licensing...

Only if the NS is not private (or trial I would say). So we would need to check the type of NS (trial, private or free) during instantiation. I think I don't have that info in the NS response right now.

**Comment by carlos-f-parada** [comment]
@anapolg "Only if the NS is not private" It is the NS that is private? Or it is the associated licensing?
@ekapassa Could it be possible for the SLA to have just Licensing? If you think this can solve the problem...
@jbonnet does it make sense for you?

**Comment by anapolg** [comment]
> @anapolg "Only if the NS is not private" It is the NS that is private? Or it is the associated licensing?

@carlos-f-parada Use the NS for the comm-pilot as an example. We would charge the users, through a license in this case, to use our service. Therefore, we have to indicate in our NS somehow that it is needed to pay for it, to get a license to use it. Otherwise the user (nor the Portal) wouldn't know.

**Comment by carlos-f-parada** [comment]
@anapolg Yes. But the NS (as far as I know) has not this meaning. What provides this meaning is the SLA/Licensing associated. Is because of that that you say that SLA (Licensing) cannot be optional?

**Comment by ekapassa** [comment]
@carlos-f-parada right now the SLA cannot include only licensing info. I will check this case (what breaks, IF breaks something, how feasible it is considering out time) and let you know today EoB if this is possible. would this be ok?

**Comment by carlos-f-parada** [comment]
Thanks @ekapassa, this check is really helpful. With this flexibility maybe we can say that SLA is mandatory (unless no SLAs at all are defined for a particular NS).

**Comment by anapolg** [comment]
> @anapolg Yes. But the NS (as far as I know) has not this meaning. What provides this meaning is the SLA/Licensing associated. Is because of that that you say that SLA (Licensing) cannot be optional?

Yes, there are two ways of continuing with this from my point of view:
A) always choose an SLA during instantiation or
B) check if the NS would need of a license (if it is private, and therefore include types in NS). Otherwise, if the NS is public, the Portal allows to leave the SLA field empty if the user wants so.

> Thanks @ekapassa, this check is really helpful. With this flexibility maybe we can say that SLA is mandatory (unless no SLAs at all are defined for a particular NS).

Going back to what I answered just above:
A) always choose an SLA during instantiation -> that means always having at least one SLA defined per NS. Otherwise the Portal should cancel the operation to the user to avoid the possible use of NS that were not intended to be license free. 
B) Check if the NS would need of a license (if NS is private) or not (if NS is public). Only leave the SLA field empty if the user wants and the NS is public. 
In case the NS is private, Portal should avoid any attempt of instantiation if there isn't any SLA for that NS or if the user tries to instantiate without one.

**Comment by mtouloup** [comment]
Let me add something as well... The licensing status of a NS can be set in the SLA, nowhere else. So, in order to know the license status of a service you need to add it in the SLA. I get Ana's doubt (that if the service is private but no SLA is selected) but since we do not define the license status of the Service in the NSD, i cant think of any other way to check if the NS is actually private....

**Comment by carlos-f-parada** [comment]
@anapolg But right now this NS being public or private does not exist concept (this concept is oprovided by the SLA), so I prefer (because it is easier) option A. In addition, we can skip the rule for the SLA to be mandatory in case no any SLA exists for a given NSD, just to facilitate and ensure that if you on-board a NS and don't care about defining SLAs, it will be deployed. NSs with interest to have licensing and get paid will care about SLAs and will define them. This will require the study @ekapassa is doing about making other stuff than Licencing optional.

**Comment by anapolg** [comment]
Ok I agree with option A. Actually is simpler from the Portal point of view. Regarding the rest:

> In addition, we can skip the rule for the SLA to be mandatory in case no any SLA exists for a given NSD, just to facilitate and ensure that if you on-board a NS and don't care about defining SLAs, it will be deployed....

In this case, if the SLA was not yet created / there was an error in the creation / someone forgot to create it..., the user will be able to use without a license a private product, at least for a while until someone notices. In my opinion this is a mistake regarding the NS providers' interests and I would consider it as a bug on the Portal side to allow this. We should have an extra check somewhere to ensure this kind of things do not happen.

**Comment by carlos-f-parada** [comment]
Ok @anapolg , lets go for option A then (my option is because it is simpler now.

Just by on-boarding an NS you don't know if it is public or private. Only after SLA association it will be public or private. The idea is to assume that no SLA means public. Otherwise even for testing this will be ugly because then on you will need (MUST) to create always an SLA before starting to deploy it.

**Comment by carlos-f-parada** [comment]
> Let me add something as well... The licensing status of a NS can be set in the SLA, nowhere else. So, in order to know the license status of a service you need to add it in the SLA. I get Ana's doubt (that if the service is private but no SLA is selected) but since we do not define the license status of the Service in the NSD, i cant think of any other way to check if the NS is actually private....

Yes, exactly @mtouloup

**Comment by anapolg** [comment]
Ok, I'll include then:
- SLA is something mandatory if there are SLAs associated to that NS.
- SLA is optional if there are no SLAs associated to that NS.
- SLA checks defined above (in the issue description) if an SLA was selected.

Is this right? Am I missing something?

**Comment by carlos-f-parada** [comment]
@anapolg Exactly! I think this is the easiest way to tackle it.
Let's wait for @ekapassa evaluation since to make SLA mandatory it is desirable that the SLA part can be void in case does not want to check KPIs for service violations.

**Comment by ekapassa** [comment]
@carlos-f-parada @jbonnet @anapolg @mtouloup Good morning guys and sorry for the late response.    
I took a look in the SLAM code and give it a thought also, regarding creating SLA Templates without guarantee terms (i.e. making them optional) - only with licensing info.    
So my comments are the following:    
-  It is feasible to have it , but it requires precious time, for not only the SLA Manager.    
    - I need to change the SLAM code in order support the gurantees as optional --> development: medium effort BUT testing: high effort
    - I need to update the sla schema.
    - The Portal needs to make the guarantees optional.
    - The validator needs to change to the new schema. Currently we are validating the sla taking into consideration also the guarantees.    
- The most important: Even if this is something feasible (it could be supported with some time effort), I have my doubts about removing the guarantees from the SLA to be honest with you... Because an SLA by definition is a Service Level Agreements that guarantees the desired levels of the service (e.g. availability). If we remove (i.e making optional) the guarantees (i.e. SLOs = Service Level Objectives) from the SLA Template we are going actually against the definition of what an SLA stands for :/  Something risky in my opinion, considering also the upcoming review..:/ 

With that said, I would like to point out that I am not very confident with removing (i.e making optional) the guarantees (i.e. SLOs, e.g. availability) from the SLA Template, based on logical and definition doubts.    
After these thoughts, my opinion is to go with option A, as you agreed BUT continue to consider the guarantees in the SLA among with the license info.     
Although, the final call is yours @carlos-f-parada and @jbonnet . How do you want to proceed?

**Comment by carlos-f-parada** [comment]
@ekapassa I see you point. The problem is: how do you do in case you want to define a licensing model (to use the service) but not SLA (best-effort)? This should be possible.

**Comment by ekapassa** [comment]
If we think the licensing and the SLA as two different parts, it makes sense to have the one without the other. But in our case we include the licensing **into** the SLA. So if we only include the licensing info, we are going to create an SLA that it is not an actual SLA at the end because it will not include any guarantees.... This is my doubt.

**Comment by anapolg** [comment]
I agree with @ekapassa , if it is an SLA you expect to have an SLA inside, not just the license information. It makes sense to me.

**Comment by carlos-f-parada** [comment]
@jbonnet Agree @ekapassa @anapolg . But this eventual split into 2 different pieces (e.g. SLA Manager and Licencing Manager) would be even harder to accommodate in terms of effort and time, or not?

**Comment by carlos-f-parada** [comment]
@jbonnet @ekapassa @anapolg Could the Licensing somehow be seen as a SLO? This would solve the conceptual issue. Can we think about this idea and what impacts it can have for the SLA Manager and Portal?

**Comment by ekapassa** [comment]
@jbonnet @carlos-f-parada @anapolg @mtouloup More or les its the same as before (making them optional). But i prefer this concept yes, because we can tell that the licensing is a different kind of a SLO. Logically it makes sense. We support two different kind of SLOs a) service gurantee SLO and b) licensing SLO.     

Effort: 
- [ ] The SLAM needs to change the code in order support the guarantees SLOs as optional
- [ ] The SLAM needs to update the sla schema.
- [ ]  The Portal needs to make the guarantees optional.
- [ ] The validator needs to be updated. Currently we are validating the sla taking into consideration also the guarantees.     

Are we agreed to this? Can we move forward?     

P.S. @jbonnet @carlos-f-parada regarding the time........ I cannot guarantee you that this will be ready by the end of May.... I will do my best to be on time, but If I will not manage it, would be ok from you to develop it early June?

**Comment by anapolg** [comment]
@ekapassa the validator takes the schemas from tng-schemas so actually I think the only change required in there is not for the validator but for the tng-schema. Then @MiguelRivasQuobis would need to check the SLA templates again to ensure nothing is broken.

Regarding Portal it is an easy change that I'll do as soon as the SLA manager supports this.

**Comment by carlos-f-parada** [comment]
@ekapassa @anapolg Ok, let's move forward in that way.

**Comment by ekapassa** [comment]
Hello @carlos-f-parada @jbonnet @anapolg      
This is done from the SLA Manager side. We can now support the optional guarantees terms.

**Comment by anapolg** [comment]
Ok, I'll work on the Portal to make them optional in the SLA template creation (as soon as possible).

Do you know if schemas were updated with this so that @MiguelRivasQuobis can do some SLA validations to test?
