### ISSUE TITLE
[VnV Platform settings]

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-portal#450]
I can't modify or delete the OSM platform

![Annotation 2019-11-06 091729](https://user-images.githubusercontent.com/16242967/68280860-b3266400-0076-11ea-8ea5-7bad1271aed1.png)

message errors:

'there is an error deleting the platform'  and
'Unable to fetch the platform'

**Comment by anapolg** [comment]
Which environment is that? Are you having connection problems?

**Comment by sinaure** [comment]
this is a local instance (in EGM) of the VNV. Has been installed using v.5 of tng-devops with 

sudo ansible-playbook roles/vnv.yml -i environments -e "target=localhost"  -e platform=vnv  --ask-vault-pass

**Comment by sinaure** [comment]
![Capture](https://user-images.githubusercontent.com/16242967/68281580-46ac6480-0078-11ea-8fe6-504624ebd513.PNG)

**Comment by anapolg** [comment]
Could you try to edit/delete the one without spaces in the name?

**Comment by sinaure** [comment]
yes I can modify sonata

**Comment by anapolg** [comment]
I did a test with Portal and I can modify both, platforms with spaces in the name and without them.

![image](https://user-images.githubusercontent.com/35800470/68282547-339a9400-007a-11ea-8ace-0b67eaae0e3a.png)

The DELETE request is the same as in your screenshot so I do not consider this as a Portal error since the request is well formed in both cases. 

Maybe v5.0 does not support yet spaces in the name in server side so I suggest you two possible solutions:
- Update to latest version (master) of both GTK and Portal
- (Easier) Do not use spaces in the name for your platforms while you have that version

Please close the issue if any of these two solutions works for you.

**Comment by sinaure** [comment]
I am using an existing SP : sta-sp-ave

**Comment by sinaure** [comment]
@arocha7

**Comment by anapolg** [comment]
I bet that the problem is that the name is OSM Local with an space in the middle. So, if you are able to change that name (used as the platform ID) somehow or, if you can create another platform with the same data but another name, I think it should work.

**Comment by anapolg** [comment]
Besides, how did you create the platform? The host is missing the http:// before the IP. I have tested this with Portal and:
- Portal receives a 200 ok but a body of error saying that the data is incorrect
- The platform never gets created nor listed because of this

**Comment by jbonnet** [comment]
hmm... `200`with an error body?!? We need to change this into `400`! Which component is generating it?

**Comment by anapolg** [comment]
Whichever is behind POST `.../settings/platforms`
![image](https://user-images.githubusercontent.com/35800470/68288497-d1935c00-0084-11ea-80a3-e8fcbaf27c1b.png)

![image](https://user-images.githubusercontent.com/35800470/68288525-dbb55a80-0084-11ea-96e7-c8ac09b078e2.png)

**Comment by felipevicens** [comment]
Fixed, now returns 400 if http:// is not specified. Host have to be with the format http://<ip-sp>

**Comment by sinaure** [comment]
Still I've the same error do I have to point on SP pre int? 
![Capture](https://user-images.githubusercontent.com/16242967/68312270-18984600-00b3-11ea-87f6-80f5285db08a.PNG)

**Comment by anapolg** [comment]
Try to create a platform with the correct host format and probably with a name composed with dashes instead of spaces (just in case this was not supported in version v5.0). Use the same information you have in that platform and test the resulting new one.

If the error persists please move your tests to a shared environment where I can check the behavior.

**Comment by sinaure** [comment]
The behaviour I am testing is:
Can I use the VNV as exploitable asset? (installed locally): by now is not possible because I can't modify or delete the existing default platform connections (for OSM):
I've tried to add another osm platform but the save button does nothing... NO logs in console :-/

@Ana to reproduce it install the VNV locally 

sudo ansible-playbook roles/vnv.yml -i environments -e "t arget=localhost" -e platform=vnv  --ask-vault-pass

**Comment by ana** [comment]
@sinaure I think you meant @anapolg and not @ana

**Comment by anapolg** [comment]
If you can operate with the other types of platforms this means that there is nothing wrong with the Portal. For example, the requests to delete a platform are the same for every type of platforms. Therefore you have a problem with your platform in particular for some reason.

Please try to do as I told you to try to fix the platform defined. If that does not work we'll see what to do.

**Comment by anapolg** [comment]
Since you can operate with other platforms (i.e you can delete Sonata one) this does not seem as a Portal error. Portal request for DELETE for example, are the same for all type of platforms. This indicates that you have a problem with your particular OSM platform. Please fix your platform errors creating a well defined one and then we'll see if there is something else to reproduce or test in Portal. 

Regarding `I've tried to add another osm platform but the save button does nothing... NO logs in console :-/`

- Fulfill all the required fields. Then you will see the SAVE button in red color. While it is grey it is disabled.
- If the error persists, please attach a screenshot of your OSM platform form. It should look something like this:

![image](https://user-images.githubusercontent.com/35800470/68460990-7dfe4b00-0209-11ea-8344-6abe9dbab8ce.png)

**Comment by sinaure** [comment]
![Capture](https://user-images.githubusercontent.com/16242967/68478434-27583780-0230-11ea-9edb-306cea0a7f2d.PNG)

Button save does not became red

**Comment by sinaure** [comment]
I don't know if it is relatd but in my browser console I've found these errors 👍 
![Capture](https://user-images.githubusercontent.com/16242967/68478532-68e8e280-0230-11ea-9e3f-058f2178456a.PNG)

**Comment by anapolg** [comment]
You are not fulfilling the name in that capture. You need to give it a name

**Comment by anapolg** [comment]
Also, the errors you are seeing were caused because you had to log in again (auth token expired). You must have seen a pop up telling you to log in again. After you log in those errors should stop.

**Comment by sinaure** [comment]
ok now I can add a new platform... I just can't remove an old one still error 400 on 
http://192.168.1.181/api/v3/settings/platforms/OSM%20Local

**Comment by anapolg** [comment]
And with the new one, can you edit it or remove it?

**Comment by sinaure** [comment]
yes i can

**Comment by anapolg** [comment]
Then, the only thing missing you need to do is to remove the old VIM (the one giving errors) manually. It is a wrong formatted VIM and, neither the Portal nor the backend services behind, support modifying or deleting it. 

I guess you (or someone) created it manually. Or, maybe you imported it from another deployment. Anyhow, it doesn't seem that the Portal would allow you to create it so, it is normal that the Portal does not allow you to remove it either.

**Comment by sinaure** [comment]
is created with the tng-devops script (not sure where) @felipevicens

**Comment by anapolg** [comment]
Then it is not a Portal issue. You would need to remove it manually somehow. I can not help you with that.

Please close the issue when you can. Thanks
