### ISSUE TITLE
[VnV Standalone in EGM]

### ISSUE THREAD

**Issue by sinaure** [sonata-nfv/tng-portal#464]
the login fail Using the local installation of VNV
in the stack plenty of unauthorized errors 
is this a Portal issue or tng-gw-sec?

![Capture](https://user-images.githubusercontent.com/16242967/69352141-af046400-0c7c-11ea-85e5-ffd1c376891e.PNG)

**Comment by anapolg** [comment]
First of all, the login is not failing. Otherwise you would not be inside the Dashboard.

As I told you in https://github.com/sonata-nfv/tng-portal/issues/450#issuecomment-551785216, the user token expires from time to time. That is what you see in the console. Totally normal behavior.

Not an issue, expected behavior.
